# Generated by Django 4.0.3 on 2022-05-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_rubric_alter_bb_options_alter_bb_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DndSpell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=50, verbose_name='ссылка')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('lvl', models.IntegerField(verbose_name='уровень')),
                ('school', models.CharField(max_length=50, verbose_name='школа')),
                ('time_cast', models.CharField(max_length=100, verbose_name='время накладывания')),
                ('distance', models.CharField(max_length=50, verbose_name='дистанция')),
                ('components', models.CharField(max_length=100, verbose_name='компоненты')),
                ('timing', models.CharField(max_length=100, verbose_name='Длительность')),
                ('class_actor', models.CharField(max_length=100, verbose_name='Классы')),
                ('arhitype', models.CharField(max_length=100, verbose_name='Архетипы')),
                ('origin', models.CharField(max_length=100, verbose_name='источник')),
                ('instruction', models.CharField(max_length=100, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Заклинание',
                'verbose_name_plural': 'Заклинания',
            },
        ),
    ]
