# Generated by Django 4.0.3 on 2022-05-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dndspell',
            name='arhitype',
            field=models.CharField(blank=True, max_length=100, verbose_name='Архетипы'),
        ),
        migrations.AlterField(
            model_name='dndspell',
            name='class_actor',
            field=models.CharField(blank=True, max_length=100, verbose_name='Классы'),
        ),
        migrations.AlterField(
            model_name='dndspell',
            name='lvl',
            field=models.CharField(max_length=10, verbose_name='уровень'),
        ),
    ]
