# Generated by Django 4.0.3 on 2022-05-19 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0002_alter_dndspell_arhitype_alter_dndspell_class_actor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dndspell',
            old_name='arhitype',
            new_name='architype',
        ),
    ]
