# Generated by Django 4.0.3 on 2022-05-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0003_rename_arhitype_dndspell_architype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dndspell',
            name='instruction',
            field=models.TextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='dndspell',
            name='time_cast',
            field=models.CharField(max_length=200, verbose_name='время накладывания'),
        ),
    ]
