# Generated by Django 4.0.3 on 2022-05-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0004_alter_dndspell_instruction_alter_dndspell_time_cast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dndspell',
            name='components',
            field=models.CharField(max_length=200, verbose_name='компоненты'),
        ),
    ]
