# Generated by Django 4.0.3 on 2022-05-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0005_alter_dndspell_components'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dndspell',
            name='architype',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Архетипы'),
        ),
        migrations.AlterField(
            model_name='dndspell',
            name='class_actor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Классы'),
        ),
    ]
