# Generated by Django 4.0.3 on 2022-05-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0006_alter_dndspell_architype_alter_dndspell_class_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dndspell',
            name='distance',
            field=models.CharField(max_length=100, verbose_name='дистанция'),
        ),
        migrations.AlterField(
            model_name='dndspell',
            name='link',
            field=models.CharField(max_length=100, verbose_name='ссылка'),
        ),
        migrations.AlterField(
            model_name='dndspell',
            name='lvl',
            field=models.CharField(max_length=15, verbose_name='уровень'),
        ),
        migrations.AlterField(
            model_name='dndspell',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='dndspell',
            name='school',
            field=models.CharField(max_length=60, verbose_name='школа'),
        ),
    ]
