# Generated by Django 4.0.3 on 2022-05-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0007_alter_dndspell_distance_alter_dndspell_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dndspell',
            name='architype',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Архетипы'),
        ),
        migrations.AlterField(
            model_name='dndspell',
            name='origin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='источник'),
        ),
    ]
