# Generated by Django 4.0.3 on 2022-06-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0008_alter_dndspell_architype_alter_dndspell_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dndspell',
            name='class_actor',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Классы'),
        ),
    ]




