# Generated by Django 4.0.3 on 2022-06-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0013_alter_dndspell_class_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dndspell',
            name='architype',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Архетипы'),
        ),
        migrations.AlterField(
            model_name='dndspell',
            name='components',
            field=models.CharField(max_length=400, verbose_name='компоненты'),
        ),
    ]
